<?php namespace JF;
/**

Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-f19772
Date:    2016-06-11 07:03:46
Version: v1.0-rc22
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-f19772",
    "email": {
        "to": "kvolkov@ya.ru",
        "cc": "",
        "bcc": "",
        "subject": "\u0418\u0417\u041c\u0415\u041d\u0418_\u0421\u0415\u0411\u042f_\u0428\u0410\u04133",
        "template": "",
        "fromName": "yyy"
    },
    "admin": {
        "users": "admin:38709",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "\u0412\u0430\u0448\u0438 \u0434\u0430\u043d\u043d\u044b\u0435 \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u044b. \u0421\u043f\u0430\u0441\u0438\u0431\u043e \u0412\u0430\u043c!",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "green"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "\u2116 \u0427\u041a \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0430",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "description": "",
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u043d\u043e\u043c\u0435\u0440 \u0447\u043b\u0435\u043d\u0441\u043a\u043e\u0433\u043e \u043a\u043b\u0443\u0431\u0430",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-th"
                }
            },
            "cid": "c32"
        },
        {
            "label": "\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0412\u0430\u0448\u0438 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "cid": "c40"
        },
        {
            "label": "\u0424\u043e\u0442\u043e \u0430\u043d\u0444\u0430\u0441",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "description": "\u0440\u0430\u0437\u043c\u0435\u0440 \u0434\u043e 500 \u043a\u0431., \u0444\u043e\u0440\u043c\u0430\u0442\u044b .jpg.png",
                "file": {
                    "maxFileSize": "500",
                    "fileToLinkSize": "500",
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                }
            },
            "cid": "c45"
        },
        {
            "label": "\u0424\u043e\u0442\u043e \u0441\u0431\u043e\u043a\u0443",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "description": " \u0440\u0430\u0437\u043c\u0435\u0440 \u0434\u043e 500 \u043a\u0431., \u0444\u043e\u0440\u043c\u0430\u0442\u044b .jpg.png",
                "file": {
                    "maxFileSize": "500",
                    "fileToLinkSize": "500",
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                }
            },
            "cid": "c50"
        },
        {
            "label": "\u0424\u043e\u0442\u043e \u0441 \u0433\u0430\u0437\u0435\u0442\u043e\u0439",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "description": "\u0440\u0430\u0437\u043c\u0435\u0440 \u0434\u043e 500 \u043a\u0431., \u0444\u043e\u0440\u043c\u0430\u0442\u044b .jpg.png",
                "file": {
                    "maxFileSize": "500",
                    "fileToLinkSize": "500",
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                }
            },
            "cid": "c56"
        },
        {
            "label": "\u0420\u043e\u0441\u0442, \u0441\u043c ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u0440\u043e\u0441\u0442"
            },
            "cid": "c63"
        },
        {
            "label": "\u0412\u0435\u0441, \u043a\u0433 ",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u0432\u0435\u0441"
            },
            "cid": "c68"
        },
        {
            "label": "\u041e\u0431\u044a\u0435\u043c \u0442\u0430\u043b\u0438\u0438, \u0441\u043c",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u043e\u0431\u044a\u0435\u0438 \u0442\u0430\u043b\u0438\u0438"
            },
            "cid": "c75"
        },
        {
            "label": "\u041e\u0431\u044a\u0435\u043c \u0431\u0435\u0434\u0435\u0440, \u0441\u043c",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u043e\u0431\u044a\u0435\u043c \u0431\u0435\u0434\u0435\u0440"
            },
            "cid": "c82"
        },
        {
            "label": "\u0420\u0430\u0437\u043c\u0435\u0440 \u043e\u0434\u0435\u0436\u0434\u044b (\u043f\u043e \u0436\u0435\u043b\u0430\u043d\u0438\u044e)",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                },
                "placeholder": "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0412\u0430\u0448 \u0440\u0430\u0437\u043c\u0435\u0440 \u043e\u0434\u0435\u0436\u0434\u044b"
            },
            "cid": "c89"
        },
        {
            "label": "\u0412\u0430\u0448\u0438 \u0432\u043f\u0435\u0447\u0430\u0442\u043b\u0435\u043d\u0438\u044f \u043e\u0442 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043a\u043e\u043d\u043a\u0443\u0440\u0441\u0435",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "placeholder": "\u041f\u043e\u0434\u0435\u043b\u0438\u0442\u0435\u0441\u044c \u0441\u0432\u043e\u0438\u043c\u0438 \u0432\u043f\u0435\u0447\u0430\u0442\u043b\u0435\u043d\u0438\u044f\u043c\u0438 \u043e\u0442 \u0443\u0447\u0430\u0441\u0442\u0438\u044f \u0432 \u043a\u043e\u043d\u043a\u0443\u0440\u0441\u0435",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c101"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0434\u0430\u043d\u043d\u044b\u0435",
                "icon": "glyphicon glyphicon-play",
                "checkRequiredFields": "\u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430 \u0437\u0430\u043f\u043e\u043b\u043d\u0438\u0442\u0435 \u043f\u043e\u043b\u044f \u043f\u043e\u043c\u0435\u0447\u0435\u043d\u043d\u044b\u0435 \u0437\u0432\u0435\u0437\u0434\u043e\u0447\u043a\u043e\u0439"
            },
            "cid": "c100"
        }
    ],
    "lang": {
        "language": "ru"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class